class Song {
  final String title;
  final String lyrics;

  Song({required this.title, required this.lyrics});
}

class Setlist {
  final String name;
  final String imageUrl;
  final List<Song> songs;

  Setlist({required this.name, required this.imageUrl, required this.songs});
}

final List<Setlist> setlists = [
  Setlist(
    name: 'Pajama Drive',
    imageUrl: 'assets/images/setlists/pajama_drive.png',
    songs: [
      Song(title: 'Shonichi (Hari Pertama)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Hissatsu Teleport (Jurus Rahasia Teleport)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Gokigen Naname Na Mermaid (Putri Duyung yang Sedang Sedih)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Futari Nori no Jitensha (Bersepeda Berdua)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tenshi No Shippo (Ekor Malaikat)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Pajama Drive', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Junjou Shugi (Prinsip Kesucian Hati)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Temodemo no Namida (Air Mata Perasaan yang Tak Tersampaikan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kagami no Naka no Jeanne D\'Arc (Joan of Arc di Dalam Cermin)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Two years Later', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Inochi no Tsukai Michi (Cara Menggunakan Hidup)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kiss Shite Son Shichatta (Rugi Sudah dicium)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Boku no Sakura (Bunga Sakuraku)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Wasshoi J!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Suifu wa Arashi ni Yume wo Miru (Pelaut yang Melihat Mimpi di Tengah Badai)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Shiroi Shirts (Baju Putih)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Dewi Theater',
    imageUrl: 'assets/images/setlists/dewi_theater.png',
    songs: [
      Song(title: 'Yuuki No Hammer (Palu Keberanian)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Inseki No Kakuritsu (Persentase Meteor)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ai No Stripper (Stripper Cinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Theater no Megami (Dewi Theater)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Hatsukoi yo, Konnichiwa (Cinta Pertamaku, Selamat Siang)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Arashi no Yoru ni wa (Pada Malam yang Berbadai)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Candy', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Locker Room Boy', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Yokaze No Shiwaza (Perbuatan Angin Malam)', lyrics: 'Lirik tidak tersedia'),
      Song(title: '100 Meter Conbini (100 Meter ke Minimarket)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Suki Suki Suki (Suka Suka Suka)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Sayonara no Kanashibari (Membeku Karena Selamat Tinggal)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Shiokaze no Shoutaijou (Surat Undangan Sang Angin Laut)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Honest Man', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Team J Oshi', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Bokutachi no Kamihikouki (Pesawat Terbang Kertas Milik Kita)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Matahari Milikku',
    imageUrl: 'assets/images/setlists/matahari_milikku.png',
    songs: [
      Song(title: 'Dreamin\' girls', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'RUN RUN RUN', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Mirai no Kajitsu (Buah Masa Depan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Viva! Hurricane', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Idol Nante Yobanaide (Jangan Panggil Diriku Idol)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Boku to Juliette to Jet Coaster (Aku, Juliette dan Jet Coaster)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Higurashi no Koi (Cinta Higurashi)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Itoshisa no Defense (Pertahanan akan Cinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Himawari (Bunga Matahari)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Takeuchi Senpai (Kakak Kelasku)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Sonna Konna Wake De (Dengan Berbagai Alasan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Deja Vu', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Yuuhi wo Miteiruka (Apakah Kau Melihat Mentari Senja?)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Lay down', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'BINGO!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Boku no Taiyou (Matahari Milikku)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Sambil Menggandeng Erat Tanganku',
    imageUrl: 'assets/images/setlists/sambil_menggandeng_erat_tanganku.png',
    songs: [
      Song(title: 'Bokura no Kaze (Angin Kita)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Mango No.2', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Te wo Tsunaginagara (Sambil Menggandeng Erat Tanganku)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Chime wa Love Song (Bel Sekolah adalah Love Song)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Glory Days', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kono Mune no Barcode (Barcode Hati Ini)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Wimbledon he Tsuretette (Ajak Aku Pergi Menuju ke Wimbledon)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ame no Pianist (Sang Pianis Hujan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Choco no Yukue (Keberadaan Coklat Itu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Innocence', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Romance Rocket', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Koi no Keikou to Taisaku (Arah Sang Cinta dan Balasannya)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Daisuki (Aku Sangat Suka)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Rope no Yuujou (Tali Persahabatan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kayoubi no Yoru, Suiyoubi no Asa (Malam Hari Selasa, Pagi Hari Rabu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tooku ni Ite mo (Di Tempat yang Jauh pun)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Gadis Gadis Remaja',
    imageUrl: 'assets/images/setlists/gadis_gadis_remaja.png',
    songs: [
      Song(title: 'Seishun Girls (Gadis Gadis Remaja)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Beach Sandal', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kimi ga Hoshi ni Naru Made (Sampai dirimu menjadi bintang)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Blue Rose', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kinjirareta Futari (Dua orang yang Terlarang)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ame no Doubutsuen (Kebun Binatang Disaat Hujan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Fushidara na Natsu (Musim Panas yang Kacau)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Don\'t Disturb!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Virgin Love', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Hizuke Henkousen (Garis Pergantian Hari Cinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Boku no Uchiage Hanabi (Kembang Api Milikku)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Yakusoku yo (Janji Ya)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Korogaru Ishi ni nare (Jadilah Batu yang Berputar)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Cinderella wa Damasarenai (Cinderella tak akan tertipu)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Aturan Anti Cinta',
    imageUrl: 'assets/images/setlists/aturan_anti_cinta.png',
    songs: [
      Song(title: 'Nagai Hikari (Cahaya Panjang)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Squall No Aida Ni (Di Tengah Hujan Badai Tiba-tiba)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'JK Nemurihime (Gadis SMA Putri Tidur)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kimi Ni Au Tabi Koi Wo Suru (Jatuh Cinta Setiap Bertemu Denganmu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kuroi Tenshi (Malaikat Hitam)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Heart Gata Virus (Virus Tipe Hati)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Renai Kinshi Jourei (Aturan Anti Cinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tsundere!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Manatsu No Christmas Rose (Mawar Natal Musim Panas)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Switch', lyrics: 'Lirik tidak tersedia'),
      Song(title: '109 (MARUKYUU)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Hikoukigumo (Jejak Awan Pesawat)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ano Koro no Sneakers (Sneakers Waktu Itu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'JKT Sanjou! (JKT Datang!)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Namida No Shinkokyuu (Napas dalam Air Mata)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Oogoe Diamond (Teriakan Berlian)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Demi Seseorang',
    imageUrl: 'assets/images/setlists/demi_seseorang.png',
    songs: [
      Song(title: 'Tsukimisou (Evening Primrose)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Warning!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tanjoubi no Yoru (Malam Ulang Tahun)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Bird', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Nage kisu de Uchiotose (Jatuhkan dengan Kiss-Bye!)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Shinkirou (Khayalan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Rider', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Seifuku ga Jama wo suru (Seragam Ini Sangat Mengganggu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Natsu ga Ichatta (Summer Has Gone)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Koike (Adyth)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tsuki no Katachi (Bentuk Sang Rembulan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Dareka no Tame ni (Demi Seseorang ~What can I do for someone?~)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Namida uri no Shoujo (Gadis Penjual Air Mata)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Cara Meminum Ramune',
    imageUrl: 'assets/images/setlists/cara_meminum_ramune.png',
    songs: [
      Song(title: 'Kizashi (Pertanda)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Koutei no Koinu (Schoolyard Puppy)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Disco Hokenshitsu (Disco di UKS)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Omatase Setlist (Setlist yang Dinanti)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Cross', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Finland Miracle', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Manazashi, Sayonara (Menatapmu Sayonara)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Usotsuki Dachou (Burung Unta si Pembohong)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Nice to Meet You!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kodoku no Ballerina (Ballerina dalam Sepi)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ima Kimi to Irareru Koto (Sekarang Ku Bersama Denganmu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Winning Ball', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Akushu no Ai (Cinta dalam Handshake)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Bowling Ganbou (Harapan Bowling)', lyrics: 'Lirik tidak tersedia'),
      Song(title: '16-iro no Yume Crayon (16 Warna Crayon Mimpi)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ramune no Nomikata (Cara Meminum Ramune)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Bel Terakhir Berbunyi',
    imageUrl: 'assets/images/setlists/bel_terakhir_berbunyi.png',
    songs: [
      Song(title: 'Mammoth', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Saishuu Bell ga Naru (Bel Terakhir Berbunyi)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Boyfriend no Tsukurikata (Cara Mendapatkan Pacar)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Erai Hito ni Naritakunai (Tak Ingin Jadi Orang Hebat)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Return Match', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Hatsukoi Dorobou (Pencuri Cinta Pertama)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Gomen ne, Jewel (Maafkan, Permataku)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Oshibe to Meshibe to Yoru no Chou Chou (Benang Sari, Putik, dan Kupu-Kupu Malam)', lyrics: 'Lirik tidak tersedia'),
      Song(title: '18 Nin Shimai no Uta (Lagu 18 Bersaudari)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Stand Up!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Coolgirl', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kaiyuugyou no Capacity (Kapasitas Ikan Migrasi)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ai ni Ikou (Pergi untuk Bertemu)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Shamu Neko (Kucing Siam)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Melos no Michi (Jalan Melos)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Sasae (Dukungan)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Tunas di Balik Seragam',
    imageUrl: 'assets/images/setlists/tunas_di_balik_seragam.png',
    songs: [
      Song(title: 'Koi wo Kataru Shijin ni Narenakute... (Ku Tak Pantas Jadi Seorang Pujangga Cinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Goukaku Kiss (Ciuman Kelulusan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Antenna (Antena)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Seifuku no Me (Tunas di Balik Seragam)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Omoide Ijou (Lebih dari Memori)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ookami to Pride (Serigala dan Pride)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Onna no Ko no Dairokkan (Indra Keenam Seorang Gadis)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kareha no Station (Stasiun Daun Kering)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Mangekyou (Kaleidoscope)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Jealousy no Alibi (Alibi Kecemburuan)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Doubt!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Nakama no Uta (Lagu Sahabat)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Mizu no Nai Pool (Kolam yang Tak Ada Airnya)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Rakuen no Kaidan (Tangga Menuju Surga)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Pinocchio Gun (Pasukan Pinokio)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tegami no Koto (Tentang Suratku)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Saka Agari',
    imageUrl: 'assets/images/setlists/saka_agari.png',
    songs: [
      Song(title: 'Telapak Tangan', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Saka Agari', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Penyangkalan Diri Requiem', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Keringat Itu Tidak Berbohong', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'End Roll', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Si Bintang Jatuh yang Egois', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Warna Cinta', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Jika Aku Dipelukmu', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Balada Serangga', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Pura-Pura dan Kepalsuan', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Seberangi Lautan', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Party di Sudut Jalan', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Fan Letter', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Terhina', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Ganteng Tapi Nanggung', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'To Be Continued', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Sekarang Sedang Jatuh Cinta',
    imageUrl: 'assets/images/setlists/sekarang_sedang_jatuh_cinta.png',
    songs: [
      Song(title: 'Sekarang Sedang Jatuh Cinta', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Boneka Teddy Bear', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Only Today', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Cinta Pertama di Jam 7 Lewat 12', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Sampai Musim Semi Tiba', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Cinta yang Tulus, Crescendo', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Faint', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Pulang Kampung', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Rasanya Malas', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Mr. Kissman', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kamulah yang Memberitahu Aku', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'BINGO!', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Rasa Sayang yang Dulu Aku Remehkan', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'LOVE CHASE', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Seragam Ini Sangat Mengganggu', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Betapa Indahnya Dunia Tempat Kita Lahir', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Fajar Sang Idola',
    imageUrl: 'assets/images/setlists/fajar_sang_idola.png',
    songs: [
      Song(title: 'Idol no Yoake (Fajar Sang Idola)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Minasan mo go Issho ni (Bersama-sama Semuanya)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Haru Ichiban ga Fuku Koro (Angin Musim Semi Pertama)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kobushi no Seigi (Kebenaran Tinju Ini)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Zannen Shoujo (Gadis yang Celaka)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kuchi Utsushi no Chocolate (Berikan Coklat dengan Bibir)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kataomoi no Taikakusen (Garis Diagonal Cinta Searah)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tengoku Yarou (Berandalan di Surga)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Itoshiki Natasha (Natasha yang Kucinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Joshikousei wa Yamerarenai (Tak Bisa Berhenti Jadi Gadis SMA)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Suki to Ieba Yokatta (Andai Ku Dapat Ungkapkan Cinta)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Sobakasu no Kiss (Freckles\' Kiss)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tanpopo no Kesshin (Keteguhan Hati Dandelion)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'J Stars', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Yokosuka Curve (Jalan Berkelok Yokosuka)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Arigatou (Terima Kasih)', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
  Setlist(
    name: 'Ingin Bertemu',
    imageUrl: 'assets/images/setlists/ingin_bertemu.png',
    songs: [
      Song(title: 'Nageki no Figure (Boneka Yang Sedih)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Namida no Shounan', 
      lyrics: 'Ombak yang jatuhkan domino\nmenggugah rasa dihatiku\nPantai berpasir nostalgik itu\njam dari musim panas\n\nTeras di rumah pinggir laut\nlangit biru yang tak berubah\nSang matahari yang begairah\nterangi kesepian itu\n\nPasangan yang terlihat serupa, tak sadari cinta lewat sekejap\nWalau tubuh pun berdekatan, kesalahan yang indah\n\nGira gira gira\nTerbakar (warna coklat muda)\nDi kulit (bekas baju renang)\nSensasi cinta itu tak akan bisa aku lupakan\nGira gira gira\nSekarangpun (di jari kelingking)\nSelalu (tak bisa kulepas)\nIngin dicinta satu kali lagi\nAir mata shounan\n\nDengan potongan rambut pendek, bergaya bak orang dewasa\nSuara ombak ber-ulang ulang, perasaan yang menyakitkan\n\nBersamamu di tepian pantai, papan wakeboard yang dimainkan itu\nJadi terkubur oleh pasir di pojokan memori\n\nKira kira kira\nBersinar (di tempat yang jauh)\nMenyilaukan (di horizon itu)\nMasih tertinggal di dada ini dejavu menyedihkan\nKira kira kira\nDi waktu (tiap ku menoleh)\nJewelry (benda yang berkilau)\nSudah tak bisa tuk bertemu lagi\nAir mata shounan\n\nEs serut dengan rasa lemon\nKuambil menggunakan sendok\nCiuman musim panas itu\nMeleleh dalam sekejap\n\nGira gira gira\nTerbakar (warna coklat muda)\nDi kulit (bekas baju renang)\nSensasi cinta itu tak akan bisa aku lupakan\nGira gira gira\nSekarangpun (di jari kelingking)\nSelalu (tak bisa kulepas)\nIngin dicinta satu kali lagi\nAir mata shounan'),
      Song(title: 'Ingin Bertemu', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Nagisa no Cherry (Cherry Tepi Pantai)', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Kaca Berbentuk I LOVE YOU', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Rencana Cinta', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Peluklah Aku Dari Belakang', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Revolusi Rio', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Tetapi...', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'DEAR MY TEACHER', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Pintu Masa Depan', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'JKT48', lyrics: 'Lirik tidak tersedia'),
      Song(title: 'Skirt Hirari', lyrics: 'Lirik tidak tersedia'),
    ],
  ),
];
